### Modelo de Regressão com SRV 

In [47]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.svm import SVR
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import KFold, cross_val_score

In [3]:
df = pd.read_csv("housing.csv", sep=",", encoding="iso-8859-1")
df.head(2)

RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0

In [4]:
independente = df.iloc[:, 0:3].values
independente

array([[ 6.575,  4.98 , 15.3  ],
       [ 6.421,  9.14 , 17.8  ],
       [ 7.185,  4.03 , 17.8  ],
       ...,
       [ 6.976,  5.64 , 21.   ],
       [ 6.794,  6.48 , 21.   ],
       [ 6.03 ,  7.88 , 21.   ]])

In [5]:
independente.shape

(489, 3)

In [7]:
dependente = df.iloc[:, 3].values
dependente

array([ 504000.,  453600.,  728700.,  701400.,  760200.,  602700.,
        480900.,  569100.,  346500.,  396900.,  315000.,  396900.,
        455700.,  428400.,  382200.,  417900.,  485100.,  367500.,
        424200.,  382200.,  285600.,  411600.,  319200.,  304500.,
        327600.,  291900.,  348600.,  310800.,  386400.,  441000.,
        266700.,  304500.,  277200.,  275100.,  283500.,  396900.,
        420000.,  441000.,  518700.,  646800.,  732900.,  558600.,
        531300.,  518700.,  445200.,  405300.,  420000.,  348600.,
        302400.,  407400.,  413700.,  430500.,  525000.,  491400.,
        396900.,  743400.,  518700.,  663600.,  489300.,  411600.,
        392700.,  336000.,  466200.,  525000.,  693000.,  493500.,
        407400.,  462000.,  365400.,  438900.,  508200.,  455700.,
        478800.,  491400.,  506100.,  449400.,  420000.,  436800.,
        445200.,  426300.,  588000.,  501900.,  520800.,  480900.,
        501900.,  558600.,  472500.,  466200.,  495600.,  6027

In [8]:
dependente.shape

(489,)

In [9]:
x_train, x_test, y_train, y_test = train_test_split(independente, dependente, test_size=0.3, random_state=0)

In [11]:
x_train.shape, x_test.shape

((342, 3), (147, 3))

In [14]:
modelo_svr = SVR(kernel='poly')
modelo_svr.fit(x_train, y_train)

SVR(kernel='poly')

In [15]:
modelo_svr.score(x_train, y_train)

0.09376603879752266

In [16]:
modelo_svr.score(x_test, y_test)

0.087868724827049

In [18]:
previsoes = modelo_svr.predict(x_train)
previsoes

array([446251.34183088, 445088.07494779, 446483.7943732 , 437672.62683749,
       448757.01428721, 441447.79394062, 415152.65831311, 437682.53954259,
       438745.26217237, 368197.98375321, 448630.17235086, 449403.21056028,
       447871.37169061, 445813.74157227, 445745.96515615, 445424.04682466,
       443283.60586461, 445532.25361471, 428661.86874737, 446203.82754923,
       443831.91325778, 445324.7416996 , 418868.88091499, 433688.3854155 ,
       449649.29733995, 448178.45104074, 409459.82461752, 447109.45774568,
       447714.14373692, 448992.0790351 , 432500.59523084, 444936.48635595,
       397585.65743204, 446112.38306516, 440391.66415087, 417810.20444714,
       448969.50086955, 442530.60732181, 448523.24185493, 444676.21238222,
       440946.7900918 , 440028.52805375, 434042.08430815, 445539.54325672,
       428128.21546945, 443832.83805961, 414805.24165054, 444969.41507663,
       427083.04075027, 449244.52975311, 411924.15790266, 435841.83217535,
       439480.46663397, 4

In [21]:
x_scaler = StandardScaler()
x_train_scaler = x_scaler.fit_transform(x_train)

In [22]:
x_train_scaler

array([[ 0.05327517, -0.70150711, -0.05467118],
       [ 1.12799963, -0.44487061, -0.52922816],
       [ 0.60711128, -0.79792304,  0.230063  ],
       ...,
       [-0.33111532, -0.36121561, -0.33940537],
       [-0.31699486,  0.84398345, -0.29194967],
       [-0.33268427, -0.38815536, -0.90887374]])

In [23]:
y_scaler = StandardScaler()
y_train_scaler = y_scaler.fit_transform(y_train.reshape(-1, 1))

In [24]:
y_train_scaler

array([[-1.05925606e-02],
       [ 6.46900118e-01],
       [ 2.85923746e-01],
       [-1.13728667e-01],
       [ 1.44111599e-01],
       [-7.84113359e-01],
       [-1.24822584e+00],
       [-2.81324840e-01],
       [-1.39512694e-01],
       [-1.01616960e+00],
       [ 2.00056152e+00],
       [ 1.21414870e+00],
       [ 1.27860877e+00],
       [-1.52404707e-01],
       [ 9.04740384e-01],
       [ 2.29945267e-03],
       [-2.81324840e-01],
       [ 2.73031732e-01],
       [-2.81324840e-01],
       [ 2.73031732e-01],
       [ 4.27735892e-01],
       [ 2.60139719e-01],
       [-1.06773765e+00],
       [-1.17087376e+00],
       [ 3.49603506e+00],
       [ 9.04740384e-01],
       [-2.07331469e+00],
       [ 1.69895626e-01],
       [ 4.27735892e-01],
       [ 2.76119030e+00],
       [-3.45784907e-01],
       [ 2.73031732e-01],
       [-1.48028208e+00],
       [ 1.57003612e-01],
       [-1.91080747e-01],
       [-1.01616960e+00],
       [ 3.37491799e-01],
       [-2.34845740e-02],
       [ 1.9

In [25]:
y_scaler = StandardScaler()
y_train_scaler = y_scaler.fit_transform(y_train.reshape(-1, 1))

In [26]:
y_train_scaler

array([[-1.05925606e-02],
       [ 6.46900118e-01],
       [ 2.85923746e-01],
       [-1.13728667e-01],
       [ 1.44111599e-01],
       [-7.84113359e-01],
       [-1.24822584e+00],
       [-2.81324840e-01],
       [-1.39512694e-01],
       [-1.01616960e+00],
       [ 2.00056152e+00],
       [ 1.21414870e+00],
       [ 1.27860877e+00],
       [-1.52404707e-01],
       [ 9.04740384e-01],
       [ 2.29945267e-03],
       [-2.81324840e-01],
       [ 2.73031732e-01],
       [-2.81324840e-01],
       [ 2.73031732e-01],
       [ 4.27735892e-01],
       [ 2.60139719e-01],
       [-1.06773765e+00],
       [-1.17087376e+00],
       [ 3.49603506e+00],
       [ 9.04740384e-01],
       [-2.07331469e+00],
       [ 1.69895626e-01],
       [ 4.27735892e-01],
       [ 2.76119030e+00],
       [-3.45784907e-01],
       [ 2.73031732e-01],
       [-1.48028208e+00],
       [ 1.57003612e-01],
       [-1.91080747e-01],
       [-1.01616960e+00],
       [ 3.37491799e-01],
       [-2.34845740e-02],
       [ 1.9

In [27]:
x_test_scaler = x_scaler.transform(x_test)
x_test_scaler

array([[-6.24507256e-01, -6.20687880e-01,  1.17917695e+00],
       [ 9.56985082e-01, -8.43295235e-01, -2.61727885e+00],
       [-1.30072075e+00,  1.98112421e+00, -1.81053199e+00],
       [ 9.72674490e-01,  9.82935809e-01,  7.99531373e-01],
       [ 2.90185237e-01, -5.72479917e-01, -3.39405369e-01],
       [ 2.72926888e-01,  9.46070896e-01,  7.99531373e-01],
       [-2.08519115e+00,  2.33134087e+00, -1.81053199e+00],
       [-1.88341711e-01, -2.51777567e-02,  7.99531373e-01],
       [-1.08325729e-01, -2.13755962e-01, -2.44493974e-01],
       [-4.18976010e-01,  1.39296468e-01,  1.17917695e+00],
       [-1.41892805e-02,  1.26651206e+00,  7.99531373e-01],
       [-6.19800434e-01,  4.03022379e-01,  7.99531373e-01],
       [-2.99736508e-01, -7.29864736e-01,  5.14797187e-01],
       [-2.51664988e+00,  3.05162455e+00,  7.99531373e-01],
       [ 7.76556889e-01, -4.85989161e-01,  1.13172126e+00],
       [-7.45315699e-01,  6.32719141e-01,  1.27408835e+00],
       [ 7.36714050e-02, -1.24429444e-01

In [29]:
y_test_scaler = y_scaler.transform(y_test.reshape(-1, 1))
y_test_scaler

array([[-2.29756787e-01],
       [ 1.08522857e+00],
       [-1.06773765e+00],
       [ 7.50036225e-01],
       [ 1.18327572e-01],
       [-5.90733160e-01],
       [-1.27400987e+00],
       [ 1.18327572e-01],
       [-3.63765873e-02],
       [-2.68432827e-01],
       [-1.48028208e+00],
       [-1.48028208e+00],
       [-1.65296720e-01],
       [-4.87597053e-01],
       [ 7.50036225e-01],
       [-7.84113359e-01],
       [-2.16864774e-01],
       [ 2.08571666e-01],
       [ 9.25435458e-02],
       [ 1.13679662e+00],
       [ 1.20125669e+00],
       [ 1.44620494e+00],
       [-1.89282650e+00],
       [-8.79446405e-02],
       [-5.39165106e-01],
       [ 3.13505869e+00],
       [ 1.84585736e+00],
       [ 2.65805419e+00],
       [ 2.29945267e-03],
       [-6.21606139e-02],
       [-8.09897386e-01],
       [ 2.29945267e-03],
       [-1.52404707e-01],
       [ 2.52913406e+00],
       [-6.21606139e-02],
       [ 2.58070211e+00],
       [-2.42648800e-01],
       [-1.14508973e+00],
       [ 8.2

In [33]:
modelo_svr2 = SVR(kernel='rbf')
modelo_svr2.fit(x_train_scaler, y_train_scaler.ravel()) # .ravel() é para retornar matriz 1D

SVR()

In [34]:
modelo_svr2.score(x_train_scaler, y_train_scaler)

0.8714780218682296

#### Teste

In [35]:
modelo_svr2.score(x_test_scaler, y_test_scaler)

0.8141963480712318

In [36]:
previsoes_teste = modelo_svr2.predict(x_test_scaler)
previsoes_teste

array([-2.15791224e-01,  1.10142277e+00, -6.88494535e-01, -1.07563769e+00,
        3.01247352e-01, -9.98869785e-01, -5.59722487e-01, -2.77421653e-01,
       -2.73937823e-02, -4.12691897e-01, -1.16997042e+00, -5.18534667e-01,
       -2.21332947e-02, -1.40012104e+00,  2.00513309e-02, -7.36008350e-01,
       -6.93655466e-02,  5.92234013e-01, -2.48820576e-01,  1.07290408e+00,
        1.76335951e+00,  1.75215955e+00, -1.13186294e+00, -9.89244717e-02,
       -2.62519149e-01,  2.76202189e+00,  1.95334571e+00,  2.71163016e+00,
       -3.10648675e-01, -2.12642736e-01, -9.48038395e-01, -3.73399265e-01,
        1.92487075e-03,  1.41767802e+00, -1.05707405e-01,  2.19221752e+00,
        6.84125100e-02, -1.21422076e+00,  1.73245025e-01,  5.77702833e-01,
       -1.14127434e+00, -3.64357403e-01, -2.10842559e-01,  1.39103054e-01,
       -6.03862563e-01, -4.32397688e-01,  2.77358169e-01, -7.89247973e-01,
        1.58912076e+00, -2.49546698e-01,  1.47592810e+00, -1.13924390e-01,
        8.76296120e-01, -

In [37]:
y_test_scaler

array([[-2.29756787e-01],
       [ 1.08522857e+00],
       [-1.06773765e+00],
       [ 7.50036225e-01],
       [ 1.18327572e-01],
       [-5.90733160e-01],
       [-1.27400987e+00],
       [ 1.18327572e-01],
       [-3.63765873e-02],
       [-2.68432827e-01],
       [-1.48028208e+00],
       [-1.48028208e+00],
       [-1.65296720e-01],
       [-4.87597053e-01],
       [ 7.50036225e-01],
       [-7.84113359e-01],
       [-2.16864774e-01],
       [ 2.08571666e-01],
       [ 9.25435458e-02],
       [ 1.13679662e+00],
       [ 1.20125669e+00],
       [ 1.44620494e+00],
       [-1.89282650e+00],
       [-8.79446405e-02],
       [-5.39165106e-01],
       [ 3.13505869e+00],
       [ 1.84585736e+00],
       [ 2.65805419e+00],
       [ 2.29945267e-03],
       [-6.21606139e-02],
       [-8.09897386e-01],
       [ 2.29945267e-03],
       [-1.52404707e-01],
       [ 2.52913406e+00],
       [-6.21606139e-02],
       [ 2.58070211e+00],
       [-2.42648800e-01],
       [-1.14508973e+00],
       [ 8.2

### Revertendo a transformação

In [38]:
y_test_inverse = y_scaler.inverse_transform(y_test_scaler)
previsoes_inverse = y_scaler.inverse_transform(previsoes_teste.reshape(-1, 1))

In [39]:
y_test_inverse

array([[ 417900.],
       [ 632100.],
       [ 281400.],
       [ 577500.],
       [ 474600.],
       [ 359100.],
       [ 247800.],
       [ 474600.],
       [ 449400.],
       [ 411600.],
       [ 214200.],
       [ 214200.],
       [ 428400.],
       [ 375900.],
       [ 577500.],
       [ 327600.],
       [ 420000.],
       [ 489300.],
       [ 470400.],
       [ 640500.],
       [ 651000.],
       [ 690900.],
       [ 147000.],
       [ 441000.],
       [ 367500.],
       [ 966000.],
       [ 756000.],
       [ 888300.],
       [ 455700.],
       [ 445200.],
       [ 323400.],
       [ 455700.],
       [ 430500.],
       [ 867300.],
       [ 445200.],
       [ 875700.],
       [ 415800.],
       [ 268800.],
       [ 590100.],
       [ 497700.],
       [ 231000.],
       [ 315000.],
       [ 388500.],
       [ 449400.],
       [ 413700.],
       [ 352800.],
       [ 453600.],
       [ 306600.],
       [ 898800.],
       [ 514500.],
       [ 743400.],
       [ 474600.],
       [ 600

In [40]:
previsoes_inverse

array([[420174.87212807],
       [634737.89796179],
       [343175.49828345],
       [280113.15005471],
       [504396.08603148],
       [292617.99343947],
       [364151.37652378],
       [410135.79618577],
       [450863.2230036 ],
       [388101.41673155],
       [264747.14617165],
       [370860.52420003],
       [451720.11197717],
       [227257.55557269],
       [458591.63091728],
       [335435.89942756],
       [444026.37735555],
       [551795.35352618],
       [414794.66988335],
       [630092.44529088],
       [742561.7980311 ],
       [740737.41964992],
       [270954.53338452],
       [439211.47830344],
       [412563.2881634 ],
       [905235.45836988],
       [773508.94404311],
       [897027.07241   ],
       [404723.39514996],
       [420687.73421742],
       [300897.99727853],
       [394501.85450867],
       [455638.98377251],
       [686253.20534829],
       [438106.59583664],
       [812419.14319062],
       [466469.25822128],
       [257539.14000176],
       [4835

In [41]:
mean_absolute_error(y_test_inverse, previsoes_inverse)

54733.899498823404

### Métricas

In [42]:
# Erro médio Absoluto
mean_absolute_error(y_test_inverse, previsoes_inverse)

54733.899498823404

In [43]:
# Erro quadrático médio
mean_squared_error(y_test_inverse, previsoes_inverse)

5390892216.930903

In [44]:
# Raiz do erro quadrático médio (RMSE)
np.sqrt(mean_squared_error(y_test_inverse, previsoes_inverse))

73422.69551665141

### Validação Cruzada
- Padronização de escala

In [45]:
x = StandardScaler()
independente_scaler = x.fit_transform(independente.reshape(-1,1))
independente_scaler

array([[-0.90835574],
       [-1.15021011],
       [ 0.41464077],
       ...,
       [-0.99099563],
       [-0.71047488],
       [ 1.27894794]])

In [46]:
y = StandardScaler()
dependente_scaler = y.fit_transform(dependente.reshape(-1, 1))
dependente_scaler

array([[ 0.30064004],
       [-0.00449803],
       [ 1.66104726],
       [ 1.49576414],
       [ 1.85175855],
       [ 0.89820209],
       [ 0.16078509],
       [ 0.69477671],
       [-0.65291643],
       [-0.34777836],
       [-0.84362772],
       [-0.34777836],
       [ 0.00821606],
       [-0.15706706],
       [-0.43677696],
       [-0.2206375 ],
       [ 0.18621326],
       [-0.52577556],
       [-0.18249524],
       [-0.43677696],
       [-1.02162492],
       [-0.25877975],
       [-0.81819955],
       [-0.90719815],
       [-0.7673432 ],
       [-0.98348267],
       [-0.64020234],
       [-0.86905589],
       [-0.41134879],
       [-0.08078255],
       [-1.1360517 ],
       [-0.90719815],
       [-1.07248127],
       [-1.08519536],
       [-1.03433901],
       [-0.34777836],
       [-0.20792341],
       [-0.08078255],
       [ 0.38963864],
       [ 1.1651979 ],
       [ 1.68647543],
       [ 0.63120628],
       [ 0.46592316],
       [ 0.38963864],
       [-0.05535438],
       [-0

In [48]:
# Separando os dados em folds
modelo_kfold = KFold(n_splits = 18, shuffle=True, random_state= 5)

In [51]:
# Criando o modelo
modelo = SVR(kernel='rbf')
resultado = cross_val_score(modelo, independente_scaler, dependente_scaler.ravel(), cv= modelo_kfold)
resultado

ValueError: Found input variables with inconsistent numbers of samples: [1467, 489]