### REGRESSÃO COM ÁRVORE DE DECISÃO

### Importando Bibliotecas

In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.model_selection import KFold, cross_val_score

#### Base de dados 

In [21]:
df = pd.read_csv("housing.csv", sep=",", encoding="iso-8859-1")
df.head(2)

RM  LSTAT  PTRATIO      MEDV
0  6.575   4.98     15.3  504000.0
1  6.421   9.14     17.8  453600.0

In [22]:
independente = df.iloc[:, 0:3].values
independente

array([[ 6.575,  4.98 , 15.3  ],
       [ 6.421,  9.14 , 17.8  ],
       [ 7.185,  4.03 , 17.8  ],
       ...,
       [ 6.976,  5.64 , 21.   ],
       [ 6.794,  6.48 , 21.   ],
       [ 6.03 ,  7.88 , 21.   ]])

In [23]:
independente.shape

(489, 3)

In [24]:
dependente = df.iloc[:, 3].values
dependente

array([ 504000.,  453600.,  728700.,  701400.,  760200.,  602700.,
        480900.,  569100.,  346500.,  396900.,  315000.,  396900.,
        455700.,  428400.,  382200.,  417900.,  485100.,  367500.,
        424200.,  382200.,  285600.,  411600.,  319200.,  304500.,
        327600.,  291900.,  348600.,  310800.,  386400.,  441000.,
        266700.,  304500.,  277200.,  275100.,  283500.,  396900.,
        420000.,  441000.,  518700.,  646800.,  732900.,  558600.,
        531300.,  518700.,  445200.,  405300.,  420000.,  348600.,
        302400.,  407400.,  413700.,  430500.,  525000.,  491400.,
        396900.,  743400.,  518700.,  663600.,  489300.,  411600.,
        392700.,  336000.,  466200.,  525000.,  693000.,  493500.,
        407400.,  462000.,  365400.,  438900.,  508200.,  455700.,
        478800.,  491400.,  506100.,  449400.,  420000.,  436800.,
        445200.,  426300.,  588000.,  501900.,  520800.,  480900.,
        501900.,  558600.,  472500.,  466200.,  495600.,  6027

In [25]:
dependente.shape

(489,)

### Treino e Teste

In [26]:
x_train, x_test, y_train, y_test = train_test_split(independente, dependente, test_size=0.3, random_state=0)

In [27]:
x_train.shape, x_test.shape

((342, 3), (147, 3))

In [28]:
y_train.shape, y_test.shape

((342,), (147,))

In [29]:
arvore = DecisionTreeRegressor(max_depth=5, random_state=10)
arvore.fit(x_train, y_train)

DecisionTreeRegressor(max_depth=5, random_state=10)

### Treino

In [30]:
arvore.score(x_train, y_train)

0.9050951127606555

In [31]:
previsoes_train = arvore.predict(x_test)
previsoes_train

array([449000.        , 597187.5       , 311850.        , 296100.        ,
       507223.25581395, 313740.        , 340200.        , 408900.        ,
       454268.18181818, 408900.        , 245855.55555556, 313740.        ,
       449000.        , 193760.        , 529433.33333333, 348600.        ,
       454268.18181818, 507223.25581395, 411075.        , 598823.07692308,
       715130.76923077, 789600.        , 193760.        , 449000.        ,
       411075.        , 914200.        , 715130.76923077, 914200.        ,
       408900.        , 408900.        , 313740.        , 411075.        ,
       408900.        , 688380.        , 454268.18181818, 940800.        ,
       507223.25581395, 245855.55555556, 507223.25581395, 507223.25581395,
       245855.55555556, 411075.        , 453000.        , 507223.25581395,
       411075.        , 408900.        , 507223.25581395, 313740.        ,
       940800.        , 408900.        , 688380.        , 454268.18181818,
       598823.07692308, 3

### Teste

In [32]:
arvore.score(x_test, y_test)

0.8256951550328737

In [33]:
previsoes_test = arvore.predict(x_test)
previsoes_test

array([449000.        , 597187.5       , 311850.        , 296100.        ,
       507223.25581395, 313740.        , 340200.        , 408900.        ,
       454268.18181818, 408900.        , 245855.55555556, 313740.        ,
       449000.        , 193760.        , 529433.33333333, 348600.        ,
       454268.18181818, 507223.25581395, 411075.        , 598823.07692308,
       715130.76923077, 789600.        , 193760.        , 449000.        ,
       411075.        , 914200.        , 715130.76923077, 914200.        ,
       408900.        , 408900.        , 313740.        , 411075.        ,
       408900.        , 688380.        , 454268.18181818, 940800.        ,
       507223.25581395, 245855.55555556, 507223.25581395, 507223.25581395,
       245855.55555556, 411075.        , 453000.        , 507223.25581395,
       411075.        , 408900.        , 507223.25581395, 313740.        ,
       940800.        , 408900.        , 688380.        , 454268.18181818,
       598823.07692308, 3

In [34]:
y_test

array([ 417900.,  632100.,  281400.,  577500.,  474600.,  359100.,
        247800.,  474600.,  449400.,  411600.,  214200.,  214200.,
        428400.,  375900.,  577500.,  327600.,  420000.,  489300.,
        470400.,  640500.,  651000.,  690900.,  147000.,  441000.,
        367500.,  966000.,  756000.,  888300.,  455700.,  445200.,
        323400.,  455700.,  430500.,  867300.,  445200.,  875700.,
        415800.,  268800.,  590100.,  497700.,  231000.,  315000.,
        388500.,  449400.,  413700.,  352800.,  453600.,  306600.,
        898800.,  514500.,  743400.,  474600.,  600600.,  304500.,
        661500.,  489300.,  422100.,  184800.,  525000.,  249900.,
        407400.,  361200.,  428400.,  392700.,  428400.,  472500.,
        258300.,  550200.,  346500.,  199500.,  302400.,  611100.,
        396900.,  585900.,  279300.,  483000.,  462000.,  218400.,
        518700.,  420000.,  392700.,  980700.,  455700.,  514500.,
        480900.,  520800.,  485100.,  525000.,  390600.,  5691

### Métricas

In [35]:
erro_medio = mean_absolute_error(y_test, previsoes_test)
erro_quadratico = mean_squared_error(y_test, previsoes_test)
raiz_erro = np.sqrt(mean_squared_error(y_test, previsoes_test))

print(f"Erro médio absoluto: {erro_medio}")
print(f"Erro quadrático médio: {erro_quadratico}")
print(f"Raiz do erro quadrático médio (RMSE): {raiz_erro}")

Erro médio absoluto: 52954.00426293284
Erro quadrático médio: 5057266756.343771
Raiz do erro quadrático médio (RMSE): 71114.46235713077


### Validação Cruzada

In [36]:
modelo_kfold = KFold(n_splits=15, shuffle=True, random_state=5)

### Criando o modelo

In [37]:
modelo = DecisionTreeRegressor(max_depth=5)
resultado = cross_val_score(modelo, independente, dependente, cv=modelo_kfold)
resultado

array([0.9107871 , 0.91994845, 0.70416127, 0.79571349, 0.64537243,
       0.62424022, 0.83188854, 0.77916943, 0.75453468, 0.45125985,
       0.92525406, 0.72678715, 0.74446726, 0.84424137, 0.56581873])

In [38]:
# Usamos a média e o desvio padrão 
print("Coeficiente de Determinação Médio: %.2f%%" % (resultado.mean() * 100.0))

Coeficiente de Determinação Médio: 74.82%


***RESULTADOS:***

**REGRESSÃO LINEAR SIMPLES:** R^2 = 0,57/0,60; RMSE = 99315,5; R^2 Validação Cruzada: 55,97%

**REGRESSÃO LINEAR MÚLTIPLA:** R^2 = 0,73/0,68; RMSE = 96087,3; R^2 Validação Cruzada: 69,25%

**REGRESSÃO POLINOMIAL:** R^2 = 0,59/0,54; RMSE = 114670,6.

**REGRESSÃO SVR:** R^2 = 0,87/0,81; RMSE = 73422,7. R^2 Validação Cruzada: 82,37%.

**REGRESSÃO ÁRVORE DE DECISÃO:** R^2 = 0,91/0,83; RMSE = 71114,5. R^2 Validação Cruzada: 74,60%.